#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:/Users/oremj/Documents/play/gwt/gwt-user.jar:/Users/oremj/Documents/play/gwt/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" com.oremj.BlackJackApplication;
